# Generated by Django 6.1.1 on 2026-09-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description_hindi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_hindi',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
