# Generated by Django 6.1.1 on 2026-09-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='consultation_type',
            field=models.CharField(default='other', max_length=100),
            preserve_default=False,
        ),
    ]
