# Generated by Django 6.1.1 on 2026-09-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ritual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_hindi', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('description_hindi', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='rituals/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
